server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

  profiles:
    active: @spring.profiles.active@

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true